/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myapplication_Utils */

#ifndef _Included_com_example_administrator_myapplication_Utils
#define _Included_com_example_administrator_myapplication_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myapplication_Utils
 * Method:    nativeColorSpaceConvertion
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_myapplication_Utils_nativeColorSpaceConvertion
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
